export { AccountingDesk } from './AccountingDesk';
export { AccountingOverview } from './AccountingOverview';
export { InvestmentsTab } from './InvestmentsTab';
export { CompanyPurchasesTab } from './CompanyPurchasesTab';
export { CompanyLossesTab } from './CompanyLossesTab';
export { LossMakingOrdersTab } from './LossMakingOrdersTab';
export { PaymentPlatformTab } from './PaymentPlatformTab';
export { OtherReceivablesTab } from './OtherReceivablesTab';
export { ExpensesTab } from './ExpensesTab';
